
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 26 19:57:32 CST 2011
//----------------------------------------------------

package sintactico_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Sym_Coma = 3;
  public static final int Sym_Var = 21;
  public static final int Sym_Mas = 8;
  public static final int Sym_PuntoYComa = 4;
  public static final int Sym_Menos = 9;
  public static final int Sym_Return = 29;
  public static final int Sym_If = 25;
  public static final int Sym_Menor = 14;
  public static final int Sym_Punto = 2;
  public static final int Sym_Diferente = 13;
  public static final int Sym_Igual = 5;
  public static final int Sym_Do = 28;
  public static final int Sym_While = 27;
  public static final int Sym_MenorIgual = 15;
  public static final int Sym_End = 24;
  public static final int Sym_Number = 20;
  public static final int Sym_MayorIgual = 17;
  public static final int Sym_Write = 30;
  public static final int Sym_Begin = 23;
  public static final int Sym_Function = 22;
  public static final int Sym_Odd = 31;
  public static final int EOF = 0;
  public static final int Sym_Mayor = 16;
  public static final int Sym_Then = 26;
  public static final int error = 1;
  public static final int Sym_ParenI = 6;
  public static final int Sym_ParenF = 7;
  public static final int Sym_Const = 18;
  public static final int Sym_Multiplicacion = 10;
  public static final int Sym_Name = 19;
  public static final int Sym_Division = 11;
  public static final int Sym_DosPIgual = 12;
}

